### ISSUE TITLE
cocoapods installation fails

### ISSUE THREAD

**Issue by Sega-Zero** [GerTeunis/OpenSSL-OSX-Pod#5]
> Installing OpenSSL-OSX (1.0.204.1)
> 
> [!] Error installing OpenSSL-OSX
> [!] /usr/bin/curl -f -L -o /var/folders/kh/9rw5rwln3_74r_g69jn93t8h0000gn/T/d20160117-26482-1l5tnba/file.tgz https://openssl.org/source/openssl-1.0.2d.tar.gz --create-dirs
> 
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

openssl.org says, that the current download url is https://openssl.org/source/openssl-1.0.2e.tar.gz and all the previous versions are being placed into https://openssl.org/source/old/openssl-*.tar.gz

Wouldn't it be better to attach an archive to release tag and not being dependent on openssl.org?

**Comment by GerTeunis** [comment]
Fixed, more structural changes will follow soon.
