### ISSUE TITLE
Pod installation fails due to OpenSSL source redirect

### ISSUE THREAD

**Issue by lksnmnn** [GerTeunis/OpenSSL-OSX-Pod#7]
Hi,

for the last few days I tried to fix the issue of installing / updating our Pods.
Long story short: I think the install script needs to be modified, as it tries to download the OpenSSL source like this:

```
curl "https://openssl.org/source/openssl-${VERSION}.tar.gz"
```

But OpenSSL.org is now redirecting to its _www_ subdomain and curl does not follow redirects by default and downloads the HTTP status page instead. The correct link is:

```
https://www.openssl.org/source/openssl-${VERSION}.tar.gz
```

It would be great if you could update the link or add the `-L` option to the curl call, which should follow the redirect AFAIK.

Cheers,
Lukas

**Comment by lksnmnn** [comment]
Created a pull request: https://github.com/GerTeunis/OpenSSL-OSX-Pod/pull/8

**Comment by GerTeunis** [comment]
Thanks! I'll create a new version in a few hours. There is a newer version of openssl as well. I've been preparing a new installer script a while back which creates a real universal lib for both mac and ios. compiled from source. will follow later.

**Comment by lksnmnn** [comment]
Nice! Thank you :)

Closed with https://github.com/GerTeunis/OpenSSL-OSX-Pod/commit/aa5a5ade71d3e1f001df1643ac864a0e52aa5387

**Comment by lksnmnn** [comment]
Me again, could you update the pod? That would be great :) We need to debug our app on Sierra, before we can release it... Thanks in advance!

**Comment by GerTeunis** [comment]
Pushed 1.0.209 a few moments ago. Please keep me posted.
